### ISSUE TITLE
Installation failure of the latest build

### ISSUE THREAD

**Issue by bhattiprolup** [xbib/elasticsearch-plugin-sru#2]
Upgraded to elastic 1.5.2 and installed the plugin, the installation reports no errors.
On startup i see a error about loaded version (groovy-all) being 2.4.0  and module failed while trying to load 2.4.1
i got around that issue by replacing the groovy-all-2.4.1.jar with groovy-all-2.4.0.jar.
After installing the plugin, I am not able to access sru plugin with the url : localhost:9200/index1/_sru

I tried to see plugin status from node info api and it shows missing url tag 
"plugins" : [ {
        "name" : "sru",
        "version" : "${project.version}",
        "description" : "SRU for Elasticsearch",
        "jvm" : true,
        "site" : false
      }, {
        "name" : "marvel",
        "version" : "1.3.1",
        "description" : "Elasticsearch Management & Monitoring",
        "url" : "/_plugin/marvel/",
        "jvm" : true,
        "site" : true
      }

**Comment by jprante** [comment]
SRU is a Ratpack application http://ratpack.io/ and opens another port, which is by default `5051`. You can change it in the settings with the parameter `plugins.sru.port`:
https://github.com/xbib/elasticsearch-plugin-sru/blob/master/src/main/groovy/org/xbib/elasticsearch/module/sru/SRUService.groovy#L112

**Comment by bhattiprolup** [comment]
so is the URL format still the same --> <host>:<port 5051>/<index_name>/_sru?operation=searchRetrieve&version=2.0&query=type1.uid=20408&startRecord=1&maximumRecords=30&pretty

**Comment by bhattiprolup** [comment]
set the plugins.sru.port property to 9200 in elasticsearch.yml and restarted the service.
submitted the query , but i get the same error 

{
  "error" : "ElasticsearchIllegalArgumentException[No feature for name [_sru]]",
  "status" : 400
}

URL used is 
curl -XGET 'localhost:9200/index1/_sru?operation=searchRetrieve&version=2.0&query=type1.uid=20408&startRecord=1&maximumRecords=30&pretty'

**Comment by jprante** [comment]
The format is `_sru/index` https://github.com/xbib/elasticsearch-plugin-sru/blob/master/src/main/groovy/org/xbib/elasticsearch/module/sru/SRUService.groovy#L124

Note, port 9200 is not recommended, since it is used by Elasticsearch HTTP.

**Comment by bhattiprolup** [comment]
changed the port to 9500, restarted the service.Now i get connection refused error.
I ran grep on netstat, i don't see a port bind on 5051 or 9500 .
New URL syntax

curl -XGET 'localhost:9500/_sru/index1?operation=searchRetrieve&version=2.0&query=type1.uid=20408&startRecord=1&maximumRecords=30&pretty'

curl: (7) Failed to connect to localhost port 9500: Connection refused

**Comment by jprante** [comment]
Did you set `plugins.sru.enabled` to true in the Elasticsearch settings? Default is false.

You should look into the log, a successful SRU plugin start adds some messages there.

**Comment by bhattiprolup** [comment]
resolved the port block issue and finally got it to work. thanks for all the help.

Any plans on fixing the groovy-all-2.4.0 issue i reported in my first post.
Right now i am fixing the jar version in the plugins directory after installation.

**Comment by bhattiprolup** [comment]
The problem was with a clashing groovy version from rat pack.
Modified the build.grade script to fix this .

compile 'io.ratpack:ratpack-groovy:0.9.15', {exclude group: "org.codehaus.groovy"}
compile 'org.codehaus.groovy:groovy-all:2.4.0'

releaseJars group: 'io.ratpack', name: 'ratpack-groovy', version: '0.9.15' , {exclude group: "org.codehaus.groovy"}
 releaseJars group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.4.0'

**Comment by jprante** [comment]
I will soon update to ratpack 0.9.17 which depends on groovy 2.4.3

The best method is to remove the older groovy and replace it with a newer one.
