### ISSUE TITLE
http-basic authentication on SRU plugin

### ISSUE THREAD

**Issue by bhattiprolup** [xbib/elasticsearch-plugin-sru#3]
Hi
i am trying to add a basic authentication mechanism on the SRU port in my deployment.
Are there any security properties by default in SRU plugin ?
Is the SRU plugin compatible with the http-basic authentication plugin ?
https://github.com/Asquera/elasticsearch-http-basic/releases

Thanks in advance
Pradeep

**Comment by jprante** [comment]
SRU plugin does not use ES HTTP module. 

Beside using nginx/apache as frontend HTTP server with authentication, you could also try to implement pac4j with Ratpack 

See http://beckje01.com/talks/greach-2015-sec-ratpack.html#/ and https://github.com/pac4j/ratpack-pac4j-demo/blob/master/src/main/java/org/leleuj/RatpackPac4jDemo.java
